<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>4gl</string>
	</array>
	<key>name</key>
	<string>Genero 4gl</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numerics</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*&amp;\s*(elif|else|endif|ifdef|ifndef|include|undef)\b</string>
			<key>name</key>
			<string>meta.preprocessor</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*&amp;\s*define\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>TODO: make it better</string>
			<key>end</key>
			<string>[^\\\{]$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numerics</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#</string>
					<key>name</key>
					<string>meta.preprocessor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.preprocessor</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\)[ \t]*\n</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#.*$</string>
					<key>name</key>
					<string>comment.line.number-sign.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>--.*$</string>
					<key>name</key>
					<string>comment.line.double-dash.4gl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>comment.block.4gl</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i)(AND|OR|MOD|NOT)\b</string>
					<key>name</key>
					<string>keyword.operator.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(BOOLEAN|BYTE|CHAR|VARCHAR|NVARCHAR|LVARCHAR|FLOAT|INTEGER|INT|INT8|SMALLINT|BIGINT|TINYINT|SMALLFLOAT|DECIMAL|MONEY|DATE|DATETIME|INTERVAL|SERIAL8|SERIAL|STRING|TEXT)\b</string>
					<key>name</key>
					<string>storage.type.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(ABSOLUTE|ACCELERATOR|ACCEPT|ACCESSORYTYPE|ACTION|ADD|AFTER|ALL|ALTER|AND|ANSI|ANY|APPEND|APPLICATION|ARRAY|AS|ASC|ASCENDING|ASCII|AT|ATTRIBUTE|ATTRIBUTES|AUDIT|AUTHORIZATION|AUTO|AVG)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(BEFORE|BEGIN|BETWEEN|BIGINT|BIGSERIAL|BLACK|BLINK|BLUE|BOLD|BOOLEAN|BORDER|BOTTOM|BREAKPOINT|BUFFER|BUFFERED|BY|BYTE)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(CACHE|CALL|CANCEL|CASCADE|CASE|CAST|CATCH|CENTURY|CHANGE|CHAR|CHARACTER|CHECK|CHECKMARK|CIRCUIT|CLEAR|CLIPPED|CLOSE|CLUSTER|COLLAPSE|COLUMN|COLUMNS|COMMAND|COMMENT|COMMIT|COMMITTED|CONCURRENT|CONNECT|CONNECTION|CONSTANT|CONSTRAINED|CONSTRAINT|CONSTRUCT|CONTEXTMENU|CONTINUE|CONTROL|COUNT|CREATE|CROSS|CURRENT|CURSOR|CYAN|CYCLE)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(DATABASE|DATE|DATETIME|DAY|DBA|DBSERVERNAME|DEC|DECIMAL|DECLARE|DEFAULT|DEFAULTS|DEFAULTVIEW|DEFER|DEFINE|DELETE|DELIMITER|DESC|DESCENDING|DESCRIBE|DESTINATION|DETAILACTION|DETAILBUTTON|DIALOG|DICTIONARY|DIM|DIMENSION|DIRTY|DISCLOSUREINDICATOR|DISCONNECT|DISPLAY|DISTINCT|DORMANT|DOUBLE|DOUBLECLICK|DOWN|DRAG_ENTER|DRAG_FINISHED|DRAG_OVER|DRAG_START|DROP|DYNAMIC)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(ELSE|END|ERROR|ESCAPE|EVERY|EXCLUSIVE|EXECUTE|EXISTS|EXIT|EXPAND|EXPLAIN|EXTEND|EXTENT|EXTERNAL)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(FALSE|FETCH|FGL|FGL_DRAWBOX|FIELD|FIELD_TOUCHED|FILE|FILL|FINISH|FIRST|FLOAT|FLUSH|FOCUSONFIELD|FOR|FOREACH|FOREIGN|FORM|FORMAT|FOUND|FRACTION|FREE|FROM|FULL|FUNCTION)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(GET_FLDBUF|GLOBALS|GO|GOTO|GRANT|GREEN|GROUP)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(HANDLER|HAVING|HEADER|HELP|HIDE|HOLD|HOUR)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(IDLE|IF|IIF|IMAGE|IMMEDIATE|IMPORT|IN|INCREMENT|INDEX|INFIELD|INITIALIZE|INNER|INOUT|INPUT|INSERT|INSTANCEOF|INT|INT8|INTEGER|INTERFACE|INTERRUPT|INTERVAL|INTO|INVISIBLE|IS|ISOLATION)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(JAVA|JOIN)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(KEEP|KEY)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(LABEL|LAST|LEFT|LENGTH|LET|LIKE|LIMIT|LINE|LINENO|LINES|LOAD|LOCATE|LOCK|LOCKS|LOG|LSTR|LVARCHAR)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(MAGENTA|MAIN|MARGIN|MATCHES|MAX|MAXCOUNT|MAXVALUE|MDY|MEMORY|MENU|MESSAGE|MIDDLE|MIN|MINUTE|MINVALUE|MOD|MODE|MODIFY|MONEY|MONTH)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(NAME|NATURAL|NAVIGATOR|NCHAR|NEED|NEXT|NO|NOCACHE|NOCYCLE|NOMAXVALUE|NOMINVALUE|NOORDER|NORMAL|NOT|NOTFOUND|NULL|NUMERIC|NVARCHAR|NVL)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(OF|OFF|ON|OPEN|OPTION|OPTIONS|OR|ORD|ORDER|OTHERWISE|OUT|OUTER|OUTPUT)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(PACKAGE|PAGE|PAGENO|PAUSE|PERCENT|PICTURE|PIPE|POPUP|PRECISION|PREPARE|PREVIOUS|PRIMARY|PRINT|PRINTER|PRINTX|PRIOR|PRIVATE|PRIVILEGES|PROCEDURE|PROGRAM|PROMPT|PUBLIC|PUT)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(QUIT)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(RAISE|READ|REAL|RECORD|RECOVER|RED|REFERENCES|RELATIVE|RELEASE|RENAME|REOPTIMIZATION|REPEATABLE|REPORT|RESOURCE|RESTART|RETAIN|RETURN|RETURNING|RETURNS|REVERSE|REVOKE|RIGHT|ROLLBACK|ROLLFORWARD|ROW|ROWBOUND|ROWS|RUN)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(SAVEPOINT|SCHEMA|SCREEN|SCROLL|SECOND|SELECT|SELECTION|SEQUENCE|SERIAL|SERIAL8|SESSION|SET|SFMT|SHARE|SHIFT|SHORT|SHOW|SIGNAL|SITENAME|SIZE|SKIP|SLEEP|SMALLFLOAT|SMALLINT|SOME|SORT|SPACE|SPACES|SQL|SQLERRMESSAGE|SQLERROR|SQLSTATE|STABILITY|START|STATISTICS|STEP|STOP|STRING|STYLE|SUBDIALOG|SUM|SYNONYM)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(TABLE|TEMP|TERMINATE|TEXT|THEN|THROUGH|THRU|TIME|TIMER|TINYINT|TO|TODAY|TOP|TRAILER|TRANSACTION|TRUE|TRUNCATE|TRUSTED|TRY|TYPE)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(UNBUFFERED|UNCONSTRAINED|UNDERLINE|UNION|UNIQUE|UNITS|UNLOAD|UNLOCK|UP|UPDATE|USER|USING)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(VALIDATE|VALUES|VAR|VARCHAR|VIEW)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(WAIT|WAITING|WARNING|WEEKDAY|WHEN|WHENEVER|WHERE|WHILE|WHITE|WINDOW|WITH|WITHOUT|WORDWRAP|WORK|WRAP)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(XML)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(YEAR|YELLOW|YES)\b</string>
					<key>name</key>
					<string>keyword.control.4gl</string>
				</dict>
			</array>
		</dict>
		<key>numerics</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comments</key>
					<string>integer or floating point with optional exponent</string>
					<key>match</key>
					<string>(\+|\-)?((\b\d+(\.\d+)?)|(\.\d+))([e|E](\+|\-)?\d+)?</string>
					<key>name</key>
					<string>constant.numeric.4gl</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'(?!')</string>
					<key>name</key>
					<string>string.quoted.single.4gl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\[\\btnfr'"]|\\$|''</string>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\x[0-9a-fA-F]{1,2}</string>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"(?!")</string>
					<key>name</key>
					<string>string.quoted.double.4gl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\[\\btnfr'"]|\\$|""</string>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\x[0-9a-fA-F]{1,2}</string>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>end</key>
					<string>`</string>
					<key>name</key>
					<string>string.quoted.raw.4gl</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.genero-4gl</string>
	<key>uuid</key>
	<string>95B786C1-0001-4107-924D-1E39162F5184</string>
</dict>
</plist>
