<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>per</string>
	</array>
	<key>name</key>
	<string>Genero Forms (per)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#screen</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numerics</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*&amp;\s*(elif|else|endif|ifdef|ifndef|include|undef)\b</string>
			<key>name</key>
			<string>meta.preprocessor</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*&amp;\s*define\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>TODO: make it better</string>
			<key>end</key>
			<string>[^\\\{]$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numerics</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#</string>
					<key>name</key>
					<string>meta.preprocessor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.preprocessor</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\)[ \t]*\n</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#.*$</string>
					<key>name</key>
					<string>comment.line.number-sign.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>--.*$</string>
					<key>name</key>
					<string>comment.line.double-dash.per</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>comment.block.per</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i)(ACCELERATOR|ACCELERATOR2|ACCELERATOR3|ACCELERATOR4|ACTION|ACTIONIMAGE|ACTIONS|ACTIONTEXT|AGGREGATE|AGGREGATETEXT|AGGREGATETYPE|ALT|AND|ATTRIBUTES|AUTO|AUTOCOMMANDS |AUTOHIDE|AUTOITEMS |AUTONEXT|AUTOSCALE|AVG)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(BETWEEN|BIGINT|BLACK|BLINK|BLUE|BOOLEAN|BOTH|BUTTON|BUTTONEDIT|BUTTONTEXTHIDDEN|BY|BYTE)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(CANVAS|CENTER|CENTURY|CHAR|CHARACTER|CHARACTERS|CHECKBOX|CLASS|COLOR|COLUMNS|COMBOBOX|COMMAND|COMMENT|COMMENTS|COMPACT|COMPLETER|COMPONENTTYPE|COMPRESS|CONFIG|CONTENT|CONTEXTMENU|CONTROL|COUNT|CURRENT|CYAN)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(DATABASE|DATE|DATEEDIT|DATETIME|DATETIMEEDIT|DAY|DEC|DECIMAL|DEFAULT|DEFAULTS|DEFAULTVIEW|DELIMITERS|DISCLOSUREINDICATOR|DISPLAY|DISPLAYONLY|DOUBLE|DOUBLECLICK|DOWNSHIFT|DYNAMIC)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(EDIT|EMAIL|END|EXPANDEDCOLUMN)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(FALSE|FIELD|FIXED|FLIPPED|FLOAT|FOLDER|FONTPITCH|FORM|FORMAT|FORMONLY|FRACTION)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(GREEN|GRID|GRIDCHILDRENINPARENT|GROUP)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(HBOX|HEIGHT|HIDDEN|HORIZONTAL|HOUR)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(IDCOLUMN|IMAGE|IMAGECOLLAPSED|IMAGECOLUMN|IMAGEEXPANDED|IMAGELEAF|INCLUDE|INITIAL|INITIALIZER|INITIALPAGESIZE|INPUT|INSTRUCTIONS|INT|INTEGER|INTERVAL|INVISIBLE|IS|ISNODECOLUMN|ITEM|ITEMS)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(JUSTIFY)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(KEY|KEYBOARDHINT|KEYS)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(LABEL|LARGE|LAYOUT|LEFT|LIKE|LINES)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(MAGENTA|MATCHES|MAX|MEDIUM|MIN|MINHEIGHT|MINUTE|MINWIDTH|MONEY|MONTH)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(NO|NOENTRY|NONCOMPRESS|NONE|NORMAL|NOSWIPE|NOT|NOTEDITABLE|NOUPDATE|NULL|NUMBER|NUMERIC)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(OPTIONS|OR|ORIENTATION)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(PACKED|PAGE|PARENTIDCOLUMN|PHANTOM|PHONE|PICTURE|PIXELHEIGHT|PIXELS|PIXELWIDTH|PLACEHOLDER|POINTS|PRECISION|PROGRAM|PROGRAMS|PROGRESSBAR|PROPERTIES)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(QUERYCLEAR|QUERYEDITABLE)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(RADIOGROUP|REAL|RECORD|RED|REQUIRED|REVERSE|RIGHT)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(SAMPLE|SCHEMA|SCREEN|SCROLL|SCROLLBARS|SCROLLGRID|SEARCH|SECOND|SEPARATOR|SHIFT|SIZE|SIZEPOLICY|SLIDER|SMALL|SMALLFLOAT|SMALLINT|SPACING|SPINEDIT|SPLIT|SPLITTER|STEP|STRETCH|STRETCHCOLUMNS|STRETCHMAX|STRETCHMIN|STYLE|SUM)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(TABINDEX|TABLE|TABLES|TAG|TEXT|TEXTEDIT|THROUGH|THRU|TIMEEDIT|TIMESTAMP|TITLE|TO|TODAY|TOOLBAR|TOPMENU|TREE|TRUE|TYPE)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(UNDERLINE|UNHIDABLE|UNHIDABLECOLUMNS|UNMOVABLE|UNMOVABLECOLUMNS|UNSIZABLE|UNSIZABLECOLUMNS|UNSORTABLE|UNSORTABLECOLUMNS|UPSHIFT|URL|USER)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(VALIDATE|VALUECHECKED|VALUEMAX|VALUEMIN|VALUEUNCHECKED|VARCHAR|VARIABLE|VBOX|VERIFY|VERSION|VERTICAL)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(WANTFIXEDPAGESIZE|WANTNORETURNS|WANTTABS|WEBCOMPONENT|WHERE|WHITE|WIDGET|WIDTH|WINDOWS|WINDOWSTYLE|WIP|WITHOUT|WORDWRAP)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(X)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(Y|YEAR|YELLOW|YES)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i)(ZEROFILL)\b</string>
					<key>name</key>
					<string>keyword.control.per</string>
				</dict>
			</array>
		</dict>
		<key>numerics</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comments</key>
					<string>integer or floating point with optional exponent</string>
					<key>match</key>
					<string>(\+|\-)?((\b\d+(\.\d+)?)|(\.\d+))([e|E](\+|\-)?\d+)?</string>
					<key>name</key>
					<string>constant.numeric.per</string>
				</dict>
			</array>
		</dict>
		<key>screen</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^[ \t]*\{$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Render SCREEN/GRID as string with tags</string>
					<key>end</key>
					<string>(})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(\[)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>FIXME M2</string>
							<key>end</key>
							<string>(\])</string>
							<key>name</key>
							<string>meta.tag</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>[|:-]</string>
									<key>name</key>
									<string>punctuation.definition.tag</string>
								</dict>
								<dict>
									<key>match</key>
									<string>.</string>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\&lt;)([a-zA-Z]*)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(&gt;)</string>
							<key>name</key>
							<string>meta.tag</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>.</string>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'(?!')</string>
					<key>name</key>
					<string>string.quoted.single.per</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\[\\btnfr'"]|\\$|''</string>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\x[0-9a-fA-F]{1,2}</string>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"(?!")</string>
					<key>name</key>
					<string>string.quoted.double.per</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\[\\btnfr'"]|\\$|""</string>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\x[0-9a-fA-F]{1,2}</string>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.per</string>
	<key>uuid</key>
	<string>6037979D-3F15-435A-8A4A-A06D48A77E06</string>
</dict>
</plist>
